#version 450

struct Circle {
    vec3 position;
    float radius;
    vec4 color;
};

layout(std140, binding = 0) readonly buffer ssboBuffer {
    Circle circles_in[];
};

layout (binding = 1, rgba8) uniform writeonly image2D outputImage;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    Circle c = circles_in[index];

    // particlesOut[index].position = c.position;
}
